name: pair-diff
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.12.7=ha878542_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py38h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=39.0.1=py38h9ce1e76_0
  - cudatoolkit=11.3.1=h9edb442_10
  - ffmpeg=4.3=hf484d3e_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py38h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.43.0=h7f98852_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.23.1=py38h6c91a56_0
  - numpy-base=1.23.1=py38ha15fc14_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1o=h166bdaf_0
  - pillow=9.4.0=py38h6a678d5_0
  - pip=20.3.3=py38h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - pytorch=1.10.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py38h06a4308_0
  - setuptools=65.6.3=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.1=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.10.0=py38_cu113
  - torchvision=0.11.0=py38_cu113
  - typing_extensions=4.4.0=py38h06a4308_0
  - urllib3=1.26.14=py38h06a4308_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==1.4.0
    - addict==2.4.0
    - aiofiles==23.1.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - albumentations==1.3.0
    - altair==4.2.2
    - antlr4-python3-runtime==4.9.3
    - anyio==3.6.2
    - appdirs==1.4.4
    - async-timeout==4.0.2
    - attrs==22.2.0
    - backports-zoneinfo==0.2.1
    - basicsr==1.4.2
    - black==21.4b2
    - blinker==1.5
    - braceexpand==0.1.7
    - cachetools==5.3.0
    - click==8.1.3
    - cloudpickle==2.2.1
    - coloredlogs==15.0.1
    - contourpy==1.0.7
    - cycler==0.11.0
    - decorator==5.1.1
    - detectron2==0.6+cu113
    - diffdist==0.1
    - docker-pycreds==0.4.0
    - einops==0.3.0
    - entrypoints==0.4
    - fastapi==0.93.0
    - ffmpy==0.3.0
    - filelock==3.9.0
    - flatbuffers==23.3.3
    - fonttools==4.39.0
    - frozenlist==1.3.3
    - fsspec==2023.3.0
    - ftfy==6.1.1
    - future==0.18.3
    - fvcore==0.1.5.post20221221
    - gitdb==4.0.10
    - gitpython==3.1.31
    - google-auth==2.16.2
    - google-auth-oauthlib==0.4.6
    - gradio==3.16.2
    - grpcio==1.51.3
    - h11==0.14.0
    - httpcore==0.16.3
    - httpx==0.23.3
    - huggingface-hub==0.13.1
    - humanfriendly==10.0
    - hydra-core==1.3.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - importlib-metadata==6.0.0
    - importlib-resources==5.12.0
    - imutils==0.5.4
    - invisible-watermark==0.1.5
    - iopath==0.1.9
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.17.3
    - kiwisolver==1.4.4
    - kornia==0.6.0
    - lazy-loader==0.1
    - linkify-it-py==2.0.0
    - lmdb==1.4.0
    - markdown==3.4.1
    - markdown-it-py==2.2.0
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - mdit-py-plugins==0.3.5
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.0.4
    - multiscaledeformableattention==1.0
    - mypy-extensions==1.0.0
    - natten==0.14.4
    - networkx==3.0
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - onnx==1.13.1
    - onnxruntime==1.14.1
    - open-clip-torch==2.0.2
    - opencv-contrib-python==4.3.0.36
    - opencv-python==4.7.0.72
    - opencv-python-headless==4.7.0.72
    - orjson==3.8.7
    - packaging==23.0
    - pandas==1.5.3
    - pathspec==0.11.1
    - pathtools==0.1.2
    - pkgutil-resolve-name==1.3.10
    - portalocker==2.7.0
    - prettytable==3.6.0
    - protobuf==3.20.3
    - psutil==5.9.4
    - pyarrow==11.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.6
    - pycryptodome==3.17
    - pydantic==1.10.6
    - pydeck==0.8.0
    - pydeprecate==0.3.1
    - pydot==1.4.2
    - pydub==0.25.1
    - pygments==2.14.0
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-multipart==0.0.6
    - pytorch-lightning==1.5.0
    - pytz==2022.7.1
    - pytz-deprecation-shim==0.1.0.post0
    - pywavelets==1.4.1
    - pyyaml==6.0
    - qudida==0.0.4
    - regex==2022.10.31
    - requests-oauthlib==1.3.1
    - rfc3986==1.5.0
    - rich==13.3.2
    - rsa==4.9
    - safetensors==0.2.7
    - scikit-image==0.20.0
    - scikit-learn==1.2.2
    - scipy==1.9.1
    - semver==2.13.0
    - sentry-sdk==1.17.0
    - setproctitle==1.3.2
    - smmap==5.0.0
    - sniffio==1.3.0
    - starlette==0.25.0
    - streamlit==1.12.1
    - streamlit-drawable-canvas==0.8.0
    - sympy==1.11.1
    - tabulate==0.9.0
    - tb-nightly==2.13.0a20230309
    - tensorboard==2.12.0
    - tensorboard-data-server==0.7.0
    - tensorboard-plugin-wit==1.8.1
    - termcolor==2.2.0
    - test-tube==0.7.5
    - threadpoolctl==3.1.0
    - tifffile==2023.2.28
    - timm==0.6.12
    - tokenizers==0.12.1
    - toml==0.10.2
    - toolz==0.12.0
    - torchmetrics==0.6.0
    - tornado==6.2
    - tqdm==4.65.0
    - transformers==4.19.2
    - tzdata==2022.7
    - tzlocal==4.2
    - uc-micro-py==1.0.1
    - uvicorn==0.20.0
    - validators==0.20.0
    - wandb==0.14.0
    - watchdog==2.3.1
    - wcwidth==0.2.6
    - webdataset==0.2.5
    - websockets==10.4
    - werkzeug==2.2.3
    - yacs==0.1.8
    - yapf==0.32.0
    - yarl==1.8.2
    - zipp==3.15.0
